# Generated by Django 5.1.4 on 2025-01-15 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ebook',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='ebook',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='file_size',
            field=models.PositiveIntegerField(help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebook',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='ebook',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages in the ebook', null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebook',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='ebook',
            index=models.Index(fields=['slug'], name='ebooks_eboo_slug_8cdab4_idx'),
        ),
        migrations.AddIndex(
            model_name='ebook',
            index=models.Index(fields=['title'], name='ebooks_eboo_title_d37196_idx'),
        ),
    ]
