# Generated by Django 5.1.5 on 2025-01-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_alter_ebook_options_ebook_deleted_at_ebook_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='cover_image',
            field=models.ImageField(upload_to='ebooks/allebook/covers/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file',
            field=models.FileField(upload_to='ebooks/allebooks/files/'),
        ),
    ]
